# Generated by Django 5.2.7 on 2025-10-18 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "civility",
                    models.CharField(
                        choices=[("M", "Monsieur"), ("F", "Madame"), ("A", "Autre")],
                        default="M",
                        max_length=1,
                        verbose_name="Civilité",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Homme"), ("F", "Femme"), ("A", "Autre")],
                        default="A",
                        max_length=1,
                        verbose_name="Sexe",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Adresse"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name="Poids (kg)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(250),
                        ],
                        verbose_name="Taille (cm)",
                    ),
                ),
                (
                    "is_pregnant",
                    models.BooleanField(
                        default=False, verbose_name="Grossesse en cours ?"
                    ),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True, null=True, verbose_name="Allergies connues"
                    ),
                ),
                (
                    "medications",
                    models.TextField(
                        blank=True, null=True, verbose_name="Médicaments actuels"
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(
                        blank=True, null=True, verbose_name="Antécédents médicaux"
                    ),
                ),
                (
                    "family_history",
                    models.TextField(
                        blank=True, null=True, verbose_name="Antécédents familiaux"
                    ),
                ),
                (
                    "lifestyle_notes",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Habitudes de vie (alimentation, sommeil, sport…)",
                    ),
                ),
                (
                    "consent",
                    models.BooleanField(
                        default=False,
                        verbose_name="J’accepte que mes données soient utilisées à des fins de suivi médical",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["-created_at"],
            },
        ),
    ]
